### PR TITLE
update Jekyll from v 2.5.3 to 3.7.2

### PR DESCRIPTION
**Pull request by Strangehill**
solves #17

### CODE REVIEW

**Comment by Strangehill** [comment]
I've moved all the default theme files from their gem into the project directory.
It's pretty common, but just as legit would be to remove all of them and  update the Gemfile and config file.

**Comment by erquhart** [comment]
Thanks @Strangehill! Honestly I'd rather keep the repo slim and just update the dependency rather than copying files over. Any reason not to go that route?

**Comment by Strangehill** [comment]
just force of habit I did it this way actually. See #20

**Comment by erquhart** [comment]
Closing in favor of #20.

**Pull request closed without merging**
